apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    enterprise: qa

# namespace: devtroncd
resources:
- ../../base/

namePrefix: qa-
nameSuffix: -wf
