apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    enterprise: qa

# namespace: devtroncd
resources:
- ../../base/


patches:
- patch: |-
    - op: replace
      path: /spec/templates/0/dag/tasks/0/arguments/parameters/1/value
      value: "demo-env"
    - op: replace
      path: /spec/templates/0/dag/tasks/1/arguments/parameters/1/value
      value: "demo-env"
  target:
    group: argoproj.io
    version: v1alpha1
    kind: Workflow
    name: release

namePrefix: demo-env-
nameSuffix: -wf
