name: Daily Task

on:
  issues:
    types:
      [opened, labeled, edited] # Runs at 8 AM and 8 PM daily


env:
  GH_TOKEN: ${{ secrets.GIT_TOKEN }} # setting GH_TOKEN for the entire workflow

jobs:
  prebuild:
    runs-on: ubuntu-latest
    # env: 
    #   GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # setting GH_TOKEN for the entire job
    steps:
    - run: |
        gh api -X GET /repos/${{ GITHUB.REPOSITORY }}/topics --jq='.names'
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        gh api -X GET /repos/${{ GITHUB.REPOSITORY }}/branches --jq='.[].name'


