name: Daily Task

on:
  issues:
    types:
      [opened, labeled, edited] # Runs at 8 AM and 8 PM daily

jobs:
  daily-task:
    runs-on: ubuntu-latest
    steps:
    - name: Check for and add label
      run: |
        python3 ../daily-ticket-checker.py
      env:
        PROJECT_ID: "1"

