name: Create Release Tag

on:
  pull_request:
    types:
      - closed

jobs:
  create-release-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up Git with user info
      run: |
        git config user.email "jatinjangir0220@gmail.com"
        git config user.name "jatin-jangir"
        echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
        gh auth login --with-token <<< "$GH_TOKEN"

    - name: Get PR title
      run: |
        PR_TITLE=$(echo "${{ github.event.pull_request.title }}" | tr -d '[:space:]' | tr ' ' '_')
        echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV

    - name: Create Release File
      run: |
        for overlay in overlays/*; do
          overlay_name=$(basename "$overlay")
          output_folder="$tag/testPR/$overlay_name"
          mkdir -p "$output_folder"
          kustomize build "$overlay" > "$output_folder/kustomize_output.yaml"
          git add "$output_folder/kustomize_output.yaml"
        done

        git commit -m "Add file for ${{ github.event.pull_request.title }}" -b release-commits

    - name: Create Release Tag
      run: |
        # Get the PR title from environment variable
        PR_TITLE=$PR_TITLE

        # Create a new tag using the PR title
        git tag -a $PR_TITLE -m "Release $PR_TITLE"

        # Push the tag to the repository
        git push origin $PR_TITLE
