name: Daily Task

on:
  issues:
    types:
      [opened, labeled, edited] # Runs at 8 AM and 8 PM daily

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: gh issue create --title "My new issue" --body "Here are more details."
      env:
        GH_TOKEN: ${{ secrets.GIT_TOKEN }}
        

