name: Daily Task

on:
  issues:
    types:
      [opened, labeled, edited] # Runs at 8 AM and 8 PM daily


jobs:
  daily-task-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up Git with user info
      run: |
        git config user.email "jatin@devtron.ai"
        git config user.name "jatin-jangir-0220"

    - name: daily-ticket-checker
      run: |
        gh api graphql --paginate -f query='
          query($endCursor: String) {
            viewer {
              repositories(first: 100, after: $endCursor) {
                nodes { nameWithOwner }
                pageInfo {
                  hasNextPage
                  endCursor
                }
              }
            }
          }
        '
      env:
        GH_TOKEN: ${{ github.token }}
        PROJECT_ID: "1"
