name: Daily Task

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs at 8 AM and 8 PM daily

jobs:
  daily-task:
    runs-on: ubuntu-latest
    steps:
    - name: Check for and add label
      run: |
        if [[ ! $(gh issue label "$ISSUE_NUMBER" --list) =~ "$LABEL_NAME" ]]; then
          gh issue edit "$ISSUE_NUMBER" --add-label "$LABEL_NAME"
        fi
      env:
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        LABEL_NAME: "initial-label"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


