name: Daily Task

on:
  issues:
    types:
      [opened, labeled, edited] # Runs at 8 AM and 8 PM daily


jobs:
  daily-task-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up Git with user info
      run: |
        git config user.email "jatin@devtron.ai"
        git config user.name "jatin-jangir"
        git fetch --tags

    - name: daily-ticket-checker
      run: |
        echo $GH_TOKEN
        gh issue list
        gh project item-list 1 --format json
      env:
        GH_TOKEN: ${{ secrets.GIT_TOKEN }}
        PROJECT_ID: "1"


